[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml",]

[terminal]
shell = { program = "nu", args = ["--login",] }

[font]
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }
size = 15

[cursor]
style = { shape = "Beam", blinking = "Always" }

[window]
dynamic_padding = true
