theme = "catppuccin-macchiato"

[editor]
program = "hx"
args = []

[cursor]
shape = 'beam'
blinking = true

[shell]
program = "nu"
args = ["--login"]

[fonts]
family = "FantasqueSansM Nerd Font Mono"
size = 30

[navigation]
mode = "Plain"
use-split = false
